### ISSUE TITLE
XML issues

### ISSUE THREAD

**Issue by ingbrzy** [cjhyuky/MA-XML-MIUI9-Korean#2]
https://translators.xiaomi.eu/XML_MIUI9-Korean-ko.html

**Comment by ingbrzy** [comment]
https://translators.xiaomi.eu/XML_MIUI9-Korean-ko.html fit it ASAP or Korean will be not included this week in the ROMs..

**Comment by bradly1** [comment]
I changed the source code. The corresponding Commit history is shown below.
b619febc7c7ba134a3907334fa6a7c7a0d6fd1ac
b3164fbd8f3202a1f5164d5dfa156ccab8fa6abb

**Comment by ingbrzy** [comment]
@bradly1 thx!
