### ISSUE TITLE
탭과 공백이 섞여있습니다

### ISSUE THREAD

**Issue by wolfwork** [cjhyuky/MA-XML-MIUI9-Korean#8]
![photo_2017-12-09_02-31-36](https://user-images.githubusercontent.com/2612373/33778311-77c4f7d4-dc8b-11e7-8314-0b9644bb2665.jpg)
위 사진처럼 탭과 공백이 섞여있습니다.
jBART에서 strings.xml을 구분할 때 탭 때문에 컴파일에 문제가 생기는 것 같습니다.
![default](https://user-images.githubusercontent.com/2612373/33778351-9c41d0e6-dc8b-11e7-89e0-7e0d5dc7dc98.PNG)
산재 되어 있는 탭을 찾기 어려울 경우 위 사진처럼 변경해주시면 감사하겠습니다,

MIUIPRO 팀에서 해당 문제를 제보하였습니다.

**Comment by xiaomiqm** [comment]
안녕하세요, 샤오미물음표입니다.
버그 보고 감사드립니다.

팀 내부에서 문제 파악과 해결 방안을 확인하고 있으니 잠시만 기다려주세요.
결과가 나오는대로 전달해드리겠지만, 사람이 하는 일이다 보니 시간이 조금 소요될 예정입니다.

관심 가져 주셔서 다시 한번 감사드립니다.
문제가 해결되면 다시 회신 드리겠습니다.

-XiaomiQM

**Comment by xiaomiqm** [comment]
+혹시 MIUIPRO 팀 한국어 번역자이신가요?

**Comment by wolfwork** [comment]
네 그렇게 되었습니다. 현재 한국어 추가된 테스트롬 받아 실험 끝낸 상태입니다.

**Comment by xiaomiqm** [comment]
@wolfwork 추가적으로 여쭙고 싶은 내용들이 있어서 그런데 카카오톡 아이디 01099537208 (전화번호가 아닌 아이디입니다) 친구추가하셔서 문자 한번만 남겨주세요 :)

**Comment by cjhyuky** [comment]
사용하시되 출처는 꼭 남겨주셔야 합니다.

**Comment by cjhyuky** [comment]
그리고 말씀하신 공백부분은 bradly1님께서 다 처리해주셨습니다.

**Comment by bradly1** [comment]
2b65806776e4c0233a969863a03c73d29f90341a
